# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from store import store_pb2 as store_dot_store__pb2


class StoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/go.micro.store.Store/Read',
                request_serializer=store_dot_store__pb2.ReadRequest.SerializeToString,
                response_deserializer=store_dot_store__pb2.ReadResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/go.micro.store.Store/Write',
                request_serializer=store_dot_store__pb2.WriteRequest.SerializeToString,
                response_deserializer=store_dot_store__pb2.WriteResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/go.micro.store.Store/Delete',
                request_serializer=store_dot_store__pb2.DeleteRequest.SerializeToString,
                response_deserializer=store_dot_store__pb2.DeleteResponse.FromString,
                )
        self.List = channel.unary_stream(
                '/go.micro.store.Store/List',
                request_serializer=store_dot_store__pb2.ListRequest.SerializeToString,
                response_deserializer=store_dot_store__pb2.ListResponse.FromString,
                )
        self.Databases = channel.unary_unary(
                '/go.micro.store.Store/Databases',
                request_serializer=store_dot_store__pb2.DatabasesRequest.SerializeToString,
                response_deserializer=store_dot_store__pb2.DatabasesResponse.FromString,
                )
        self.Tables = channel.unary_unary(
                '/go.micro.store.Store/Tables',
                request_serializer=store_dot_store__pb2.TablesRequest.SerializeToString,
                response_deserializer=store_dot_store__pb2.TablesResponse.FromString,
                )


class StoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Databases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=store_dot_store__pb2.ReadRequest.FromString,
                    response_serializer=store_dot_store__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=store_dot_store__pb2.WriteRequest.FromString,
                    response_serializer=store_dot_store__pb2.WriteResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=store_dot_store__pb2.DeleteRequest.FromString,
                    response_serializer=store_dot_store__pb2.DeleteResponse.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=store_dot_store__pb2.ListRequest.FromString,
                    response_serializer=store_dot_store__pb2.ListResponse.SerializeToString,
            ),
            'Databases': grpc.unary_unary_rpc_method_handler(
                    servicer.Databases,
                    request_deserializer=store_dot_store__pb2.DatabasesRequest.FromString,
                    response_serializer=store_dot_store__pb2.DatabasesResponse.SerializeToString,
            ),
            'Tables': grpc.unary_unary_rpc_method_handler(
                    servicer.Tables,
                    request_deserializer=store_dot_store__pb2.TablesRequest.FromString,
                    response_serializer=store_dot_store__pb2.TablesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'go.micro.store.Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Store(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/go.micro.store.Store/Read',
            store_dot_store__pb2.ReadRequest.SerializeToString,
            store_dot_store__pb2.ReadResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/go.micro.store.Store/Write',
            store_dot_store__pb2.WriteRequest.SerializeToString,
            store_dot_store__pb2.WriteResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/go.micro.store.Store/Delete',
            store_dot_store__pb2.DeleteRequest.SerializeToString,
            store_dot_store__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/go.micro.store.Store/List',
            store_dot_store__pb2.ListRequest.SerializeToString,
            store_dot_store__pb2.ListResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Databases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/go.micro.store.Store/Databases',
            store_dot_store__pb2.DatabasesRequest.SerializeToString,
            store_dot_store__pb2.DatabasesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Tables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/go.micro.store.Store/Tables',
            store_dot_store__pb2.TablesRequest.SerializeToString,
            store_dot_store__pb2.TablesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
