# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "config.ChangeSet" do
    optional :data, :string, 1
    optional :checksum, :string, 2
    optional :format, :string, 3
    optional :source, :string, 4
    optional :timestamp, :int64, 5
  end
  add_message "config.Change" do
    optional :namespace, :string, 1
    optional :path, :string, 2
    optional :changeSet, :message, 3, "config.ChangeSet"
  end
  add_message "config.CreateRequest" do
    optional :change, :message, 1, "config.Change"
  end
  add_message "config.CreateResponse" do
  end
  add_message "config.UpdateRequest" do
    optional :change, :message, 1, "config.Change"
  end
  add_message "config.UpdateResponse" do
  end
  add_message "config.DeleteRequest" do
    optional :change, :message, 1, "config.Change"
  end
  add_message "config.DeleteResponse" do
  end
  add_message "config.ListRequest" do
    optional :namespace, :string, 1
  end
  add_message "config.ListResponse" do
    repeated :values, :message, 1, "config.Change"
  end
  add_message "config.ReadRequest" do
    optional :namespace, :string, 1
    optional :path, :string, 2
  end
  add_message "config.ReadResponse" do
    optional :change, :message, 1, "config.Change"
  end
  add_message "config.WatchRequest" do
    optional :namespace, :string, 1
    optional :path, :string, 2
  end
  add_message "config.WatchResponse" do
    optional :namespace, :string, 1
    optional :changeSet, :message, 2, "config.ChangeSet"
  end
end

module Config
  ChangeSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.ChangeSet").msgclass
  Change = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.Change").msgclass
  CreateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.CreateRequest").msgclass
  CreateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.CreateResponse").msgclass
  UpdateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.UpdateRequest").msgclass
  UpdateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.UpdateResponse").msgclass
  DeleteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.DeleteRequest").msgclass
  DeleteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.DeleteResponse").msgclass
  ListRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.ListRequest").msgclass
  ListResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.ListResponse").msgclass
  ReadRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.ReadRequest").msgclass
  ReadResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.ReadResponse").msgclass
  WatchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.WatchRequest").msgclass
  WatchResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.WatchResponse").msgclass
end
