name: generate

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        apt update
        apt install -y protobuf-compiler
        apt install -y --no-install-recommends python3-pip
        apt install -y --no-install-recommends nodejs npm
        pip3 install --no-cache-dir --ignore-installed grpcio grpcio-tools
        go get github.com/unistack-org/protoc-gen-all

    - name: Run generator
      id: generator
      run: protoc-gen-all -srcdir proto/ -dstdir generated/ -langs go,python,java,js

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git commit -m "regen" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

