name: generate

on:
  push:
    paths:
      - 'proto/**'
    branches:
      - master
      - develop
    tags:
      - 'v*.*.*'

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies and generate
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler
        sudo apt install -y --no-install-recommends python3 python3-pip
        sudo apt install -y --no-install-recommends nodejs npm
        sudo apt install -y --no-install-recommends ruby
        sudo python -m pip install --upgrade pip
        sudo gem install grpc grpc-tools
        pip3 install --no-cache-dir --ignore-installed grpcio grpcio-tools
        npm i grpc-tools
        rm -rf sdk
        go mod init clients
        GOBIN=$(go env GOPATH)/bin go get github.com/unistack-org/protoc-gen-all github.com/golang/protobuf/protoc-gen-go@v1.3.4 github.com/micro/protoc-gen-micro/v2
        PATH=$PATH:$(go env GOPATH)/bin:$(npm bin):/usr/local/bin/ protoc-gen-all -srcdir proto/ -dstdir sdk/ -langs go,python,java,ruby,js

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add sdk/ && git commit -m "regenerate from proto"
        git status

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
